### ISSUE TITLE
Typo in environment variable?

### ISSUE THREAD

**Issue by pylipp** [mattsb42/pipx-in-pipx#21]
Hej, I just noticed https://github.com/mattsb42/pipx-in-pipx/blob/master/setup.py#L104, is there a P missing (`BUILDING_PIPX_IN_PIPX` instead of `BUILDING_PIPX_IN_PIX`)?

**Comment by mattsb42** [comment]
Doh! Thanks for the catch!

Looks like it doesn't matter for the publishing step since I guess I just copy-pasted that value over into `tox.ini`, but yes, that should be fixed.
